kafka:
  bootstrap-servers: 192.168.99.100:9092
  topic:
    ca: customer-avro
spring:
  cloud:
    stream:
      schemaRegistryClient:
       endpoint: 192.168.99.100:8081
  kafka:
    listener:
      ack-mode: manual
    consumer:
      enable-auto-commit: false
      value-deserializer: sk.stopangin.MyDeser
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: customer-consumer-group-v2
server:
  port: 8099


